version: '3.7'

services:
  app:
    container_name: twitter_reader
    build: docker/app/
    volumes:
      - ./app:/app
  nginx:
    container_name: twitter_reader_nginx
    build: docker/nginx/
    volumes:
      - ./run/:/var/run/
